### ISSUE TITLE
Adapt README

### ISSUE THREAD

**Issue by piekvossen** [thomas097/Annotation-Tool-for-Master-Thesis#1]
- the main.py file is in the folder annotation_tool

- the data can be found in: dataset_creation/batches

**Comment by thomas097** [comment]
Hi Piek,

I am not sure I understand. I checked the folder structure of the repo and the _main.py_ file and _data_ folder are in the root folder.

This repository I made so that it isn't necessary to download my entire project (incl. models, etc.) to start annotating. It only contains the essentials for the data annotation.

Cheers,
Thomas

**Comment by piekvossen** [comment]
I pulled the changes in the earlier clone. When I do a clean clone it looks good. Sorry for the confusion.
